/* 
 * If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
 * Finish the solution so that it returns the sum of all the multiples of 3 or 5 below the number passed in.
 * Courtesy of ProjectEuler.net & Codewars
 */

function solution1(number){
  var sum = 0;
  for(var i = 1;i< number; i++){
    if(i % 3 == 0 || i % 5 == 0){
      sum += i;
    }
  }
  return sum;
}

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * Courtesy of ProjectEuler.net
 */

function solution2(limit){
    /* it did say start with 1 & 2... */
    var sequence = [1, 2];
    var sum = 0;
    for(var i = 2; i < limit; i++) {
      sequence.push(sequence[i]+sequence[i-1]);
        if (sequence[i]%2 == 0){
            sum += sequence[i];
        }
    }
    return sum;
}
